version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.1
    - 5.21.1
    - 5.24.3
    - 5.25.1
    - 5.28.0
    - 5.35.0
  - dependency-name: css-loader
    versions:
    - 5.1.4
    - 5.2.1
    - 5.2.4
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
